[workspace]
authors = ["Callum Arnold <24391445+arnold-c@users.noreply.github.com>"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64"]
preview = ["pixi-build"]

[dependencies]
radian = { path = "." }
rchitect = ">=0.4.7,<0.5"
setuptools = ">=79.0.0,<80"
pygments = ">=2.19.1,<3"
prompt_toolkit = ">=3.0.51,<4"

[package]
name = "radian"
version = "0.1.0"

[tasks]
start = "radian-main"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"
